# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Caio Tonetti
tagline:          'A Personal Blog'
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

social:
  github:         https://github.com/lionswrath
  linkedin:       https://www.linkedin.com/in/caio-tonetti/
