# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Caio Tonetti
tagline:          'A Personal Blog'
description:      'I am a brazilian student currently pursuing a masters degree.'
url:              https://chst.dev
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

social:
  github:         https://github.com/lionswrath
  linkedin:       https://www.linkedin.com/in/caio-tonetti/
